services:
  - type: web
    name: pinterest-analyzer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    branch: main
    region: oregon
    plan: free
